### ISSUE TITLE
[FEAT] 통계집계 (나이 기준)

### ISSUE THREAD

**Issue by eunkangchoi** [5th-wanted-pre-onboarding-teamG/1_statistics#20]

**Comment by loveAlakazam** [comment]
@stae1102 @MisterRuby 
나이 를 기준으로 통계할 때 url 을 `/histories/gender` 로 해야되나요?
아니면 '통계'니까 url을 `/stats/gender` 로 할까요?

후자라면(/stats) 컨트롤러를 추가해야돼요~
