### ISSUE TITLE
[FIX/TEST] 유저 및 게시물 서비스 유지보수

### ISSUE THREAD

**Issue by stae1102** [5th-wanted-pre-onboarding-teamG/1_statistics#42]
# TO DO LIST

## 유저
- [x] 유저 회원가입시 랭크에 값이 없어도 로그인 되는 문제
- [x] 유저 회원가입시 비밀번호도 같이 반환하는 문제

## 게시판
- [x] 게시물 삭제 테스트
- [x] 게시물 등록 테스트

**Comment by stae1102** [comment]
# 게시물 등록 테스트

## 게시물 종류 검증

1. 해당하지 않는 종류

<img width="852" alt="image" src="https://user-images.githubusercontent.com/83271772/198494176-1aa74c51-6ad7-42f8-956b-58e881823789.png">
 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/83271772/198494348-a7434e18-bf1c-4491-bc99-39b3816957bd.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/83271772/198494542-d8ce99ec-39d5-4130-8205-8ee0671a3c34.png">

### 문제사항
1. 해당하지 않는 종류 기입시 빈 값으로 넘어감
~~2. userId가 author 컬럼에 기입되지 않음~~
-> 하지만 세션이 없어도 생성되는 오류 - 가드 사용 필요


2. 해당하는 종류

<img width="854" alt="image" src="https://user-images.githubusercontent.com/83271772/198494752-5ad717be-0be8-416d-8687-0d69edf77345.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/83271772/198494787-eb98877a-44b6-4647-9fee-783a50651eca.png">

### 문제사항
~~1. userId가 author 컬럼에 기입되지 않음~~
-> 하지만 세션이 없어도 생성되는 오류 - 가드 사용 필요

3. 권한에 맞지 않는 종류

<img width="851" alt="image" src="https://user-images.githubusercontent.com/83271772/198495107-417e24e4-e74d-4e15-accd-ba795f56177a.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/83271772/198495129-55fa83f3-41fa-489e-a735-78e6ed69cbb8.png">

### 문제사항
1. 권한이 없어도 생성 가능.

## 🛠하지만 아직 작성하지 않은 부분이므로 추후 보완 가능 #14

# 게시물 삭제 테스트

## 게시물이 존재하는 경우

<img width="853" alt="image" src="https://user-images.githubusercontent.com/83271772/198497018-f4ab38f6-b78b-4cfe-9269-23628b0c0cc0.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/83271772/198497197-a656b345-c6e6-4747-9968-65e6c7fe2ae1.png">

일반 유저인 상태로, userId가 기록된 10번 게시물(자유)을 삭제요청(로그인 하고 바로 요청함)

<img width="853" alt="image" src="https://user-images.githubusercontent.com/83271772/198497298-5a9ce6a5-64ad-4959-a28a-2d3ad980ee94.png">

### 문제사항
1. AuthenticatedGuard의 실효성이 없음 -> user가 아니라 boolean 반환 필요**(내부 과정 수정)**
> 어려우시면 제가 구현했던 코드로 바꿔도 되는지 여쭤보고 싶습니다. @MisterRuby 
2. softDelete가 deletedAt 컬럼이 없어서 오류 발생. entity 수정 필요

**Comment by MisterRuby** [comment]
Postman 으로 확인 결과 인증 처리는 되고 있는 것으로 확인됩니다.
혹시 로그인 후 게시글 삭제 요청시 쿠키를 포함하여 요청을 보내셨는지 확인이 필요합니다.
그리고 현재 게시글 삭제 서비스에서 문제를 발견해서 그 부분은 제가 처리해야 될 것 같습니다.

**Comment by stae1102** [comment]
# 게시물 삭제 테스트 완료

<img width="852" alt="image" src="https://user-images.githubusercontent.com/83271772/198518466-5f6ddb0e-1c92-4fcc-8504-731ec854235a.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/83271772/198518624-fbd57799-63e8-47fa-8b9f-50fa2b834bda.png">


# 게시물 등록 테스트 완료

## 일반 - 자유

<img width="855" alt="image" src="https://user-images.githubusercontent.com/83271772/198518676-f529524e-6dc9-47e9-9980-62c8a6dd6228.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/83271772/198518737-d2f7b764-7d2b-4489-a630-698fcfa9b7bc.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/83271772/198518780-b472c6b1-2d90-4dd8-baab-c4127335b8ba.png">

**Comment by loveAlakazam** [comment]
@MisterRuby @stae1102 
저 궁금한게 있는데요
포스트맨에서 비밀번호 입력할때 꼭 저렇게 해싱된 값으로 input으로 해야되나요??

포스트맨(클라이언트)
{
  password: "1234"
}

=> 왜 패스워드를 암호화된 값으로 해야되는 이유가 무엇인지 알 수 잇을까요?

**Comment by stae1102** [comment]
@loveAlakazam 
질문을 잘 이해한 건지 모르겠는데,

만약에 해커가 서버 데이터베이스를 해킹하면 비밀번호를 보게 될 텐데 해시 암호화를 하지 않으면 비밀번호가 데이터베이스에 원본값으로 노출되어서 그대로 사용할 수 있지만, 해시 암호화를 하면 데이터베이스를 해킹하더라도 비밀번호가 암호화되어서 사용할 수 없기 때문입니다. 단방향 암호화라고 부릅니다.

해시화된 비밀번호를 그대로 치더라도, 로그인할 때 입력한 비밀번호를 다시 해시화하여 데이터베이스에 저장된 해시 비밀번호와 비교하기 때문에 암호화 알고리즘을 분석하여 복호화하지 않는 이상 사용할 수 없습니다.

**Comment by loveAlakazam** [comment]
입력한 비밀번호를 암호화 시킨 값이랑
데이터베이스에 저장된 해시값이랑 비교하는 미들웨어를 추가하면 되지 않을까요???

**Comment by stae1102** [comment]
그건 auth.strategy.ts 파일에서 검사하는 부분에서 처리됩니다.

```ts
// DB에 저장되어 있는 유저 정보의 비밀번호와 유저가 입력한 비밀번호가 일치하는지 비교
const validate = await bcrypt.compare(pass, findUser.password);
```

우려하는 사항은 typeorm.save의 결과를 반환하면 암호화된 비밀번호가 노출되는 것이었습니다. 이미 암호화해서 사실 외부로 노출이 되더라도 괜찮으나 복호화의 가능성이 조금이라도 있어서요.

혹시 어떤 부분에서 의문이 드셨는지 여쭤봐도 될까요? 참고하겠습니다.

**Comment by loveAlakazam** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/36457434/198534908-0d9c5489-1376-46e5-9323-807a7777180a.png">

postman 에서 테스트한 사진에서 의문이 들었어요
postman 테스트의 body 데이터의 password 값에  암호화된 값을 넣은부분이요.

예를들면.. 깃헙사이트에 로그인 한다고 가정합시다.
아이디 "hello@gmail.com", 패스워드 "1234" 를 쳐서 로그인을 하잖아요?

성태님이 테스트한 내용을 위의 예시로 들자면
클라이언트가 직접 비밀번호를 암호화 시킨 값을 입력한거나 똑같아요.
깃헙 사이트에 로그인을 했어요
아이디 "hello@gmail.com" 이고
패스워드 원문은 "1234" 인데
패스워드 원문 "1234"를 암호화시켜서 "fdjakf;jdaskfjdssafdasdvk#$/fd3143" 복잡한 문자열이 된거죠..
즉 클라이언트(사용자)는 직접 암호화된 값("fdjakf;jdaskfjdssafdasdvk#$/fd3143") 을 직접 타이핑해서 입력 한거나 다름없죠.


사용자의 편의성을 고려해본거였어요.
패스워드 원문 으로는 input 으로 하면 클라이언트의 입장에서도 편할거 같고,
포스트맨으로 테스트해야되는 저희한테도 편할거같아서요

**Comment by stae1102** [comment]
음... 저 사진 속 요청은 로그인 요청이 아니고 게시물 만드는 요청이고 body값에는 title과 content만 넣어서 요청을 보낸 것인데.....?

그래서 생성한 결과가 JSON으로 반환되었고, author에는 쿠키에 담긴 유저 정보가 들어간 것이었습니다.

**Comment by loveAlakazam** [comment]
아아 리스폰스군요...ㅎㅎ;; 제가 크게 오해했습니다
답변 감사합니다 :)
